services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_APP_NAME: "${NEXT_PUBLIC_APP_NAME:-Prostore}"
        NEXT_PUBLIC_APP_DESCRIPTION: "${NEXT_PUBLIC_APP_DESCRIPTION:-A modern ecommerce store built with Next.js}"
        NEXT_PUBLIC_SERVER_URL: "${NEXT_PUBLIC_SERVER_URL:-http://localhost:3000}"
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:-}"
    container_name: prostore-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://postgres:secret@host.containers.internal:5432/neondb?schema=public"
      NODE_OPTIONS: ""
      AUTH_TRUST_HOST: "true"
